name: helixfold
channels:
  - conda-forge
  - bioconda
  - biocore
  - paddle
  - nvidia

dependencies:
  - cuda-toolkit=12.0
  - cudnn=8.4.0
  - libgcc
  - libgomp
  - nccl=2.14
  - pip
  - python=3.9
